/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedPostsIndexRouteImport } from './routes/_authenticated/posts/index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations/index'
import { Route as AuthenticatedGlobalRolesIndexRouteImport } from './routes/_authenticated/global-roles/index'
import { Route as AuthenticatedFileLibraryIndexRouteImport } from './routes/_authenticated/file-library/index'
import { Route as AuthenticatedCompanyRolesIndexRouteImport } from './routes/_authenticated/company-roles/index'
import { Route as AuthenticatedCompanyMembersIndexRouteImport } from './routes/_authenticated/company-members/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedTicketsUuidRouteImport } from './routes/_authenticated/tickets/$uuid'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedProjectsUuidRouteImport } from './routes/_authenticated/projects/$uuid'
import { Route as AuthenticatedPostsCreateRouteImport } from './routes/_authenticated/posts/create'
import { Route as AuthenticatedPostsUuidRouteImport } from './routes/_authenticated/posts/$uuid'
import { Route as AuthenticatedGlobalRolesCreateRouteImport } from './routes/_authenticated/global-roles/create'
import { Route as AuthenticatedGlobalRolesUuidRouteImport } from './routes/_authenticated/global-roles/$uuid'
import { Route as AuthenticatedCompanyRolesCreateRouteImport } from './routes/_authenticated/company-roles/create'
import { Route as AuthenticatedCompanyRolesUuidRouteImport } from './routes/_authenticated/company-roles/$uuid'
import { Route as AuthenticatedCompaniesCreateRouteImport } from './routes/_authenticated/companies/create'
import { Route as AuthenticatedCompaniesUuidRouteImport } from './routes/_authenticated/companies/$uuid'
import { Route as AuthenticatedDemoSettingsRouteRouteImport } from './routes/_authenticated/demo/settings/route'
import { Route as AuthenticatedDemoUsersIndexRouteImport } from './routes/_authenticated/demo/users/index'
import { Route as AuthenticatedDemoTasksIndexRouteImport } from './routes/_authenticated/demo/tasks/index'
import { Route as AuthenticatedDemoSettingsIndexRouteImport } from './routes/_authenticated/demo/settings/index'
import { Route as AuthenticatedDemoHelpCenterIndexRouteImport } from './routes/_authenticated/demo/help-center/index'
import { Route as AuthenticatedDemoChatsIndexRouteImport } from './routes/_authenticated/demo/chats/index'
import { Route as AuthenticatedDemoAppsIndexRouteImport } from './routes/_authenticated/demo/apps/index'
import { Route as AuthenticatedDemoSettingsNotificationsRouteImport } from './routes/_authenticated/demo/settings/notifications'
import { Route as AuthenticatedDemoSettingsDisplayRouteImport } from './routes/_authenticated/demo/settings/display'
import { Route as AuthenticatedDemoSettingsAppearanceRouteImport } from './routes/_authenticated/demo/settings/appearance'
import { Route as AuthenticatedDemoSettingsAccountRouteImport } from './routes/_authenticated/demo/settings/account'
import { Route as AuthenticatedCompaniesCompanyUuidRolesIndexRouteImport } from './routes/_authenticated/companies/$companyUuid/roles/index'
import { Route as AuthenticatedCompaniesCompanyUuidRolesCreateRouteImport } from './routes/_authenticated/companies/$companyUuid/roles/create'
import { Route as AuthenticatedCompaniesCompanyUuidRolesUuidRouteImport } from './routes/_authenticated/companies/$companyUuid/roles/$uuid'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGlobalRolesIndexRoute =
  AuthenticatedGlobalRolesIndexRouteImport.update({
    id: '/global-roles/',
    path: '/global-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFileLibraryIndexRoute =
  AuthenticatedFileLibraryIndexRouteImport.update({
    id: '/file-library/',
    path: '/file-library/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRolesIndexRoute =
  AuthenticatedCompanyRolesIndexRouteImport.update({
    id: '/company-roles/',
    path: '/company-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyMembersIndexRoute =
  AuthenticatedCompanyMembersIndexRouteImport.update({
    id: '/company-members/',
    path: '/company-members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketsUuidRoute =
  AuthenticatedTicketsUuidRouteImport.update({
    id: '/tickets/$uuid',
    path: '/tickets/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsUuidRoute =
  AuthenticatedProjectsUuidRouteImport.update({
    id: '/projects/$uuid',
    path: '/projects/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsCreateRoute =
  AuthenticatedPostsCreateRouteImport.update({
    id: '/posts/create',
    path: '/posts/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsUuidRoute = AuthenticatedPostsUuidRouteImport.update({
  id: '/posts/$uuid',
  path: '/posts/$uuid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGlobalRolesCreateRoute =
  AuthenticatedGlobalRolesCreateRouteImport.update({
    id: '/global-roles/create',
    path: '/global-roles/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGlobalRolesUuidRoute =
  AuthenticatedGlobalRolesUuidRouteImport.update({
    id: '/global-roles/$uuid',
    path: '/global-roles/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRolesCreateRoute =
  AuthenticatedCompanyRolesCreateRouteImport.update({
    id: '/company-roles/create',
    path: '/company-roles/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRolesUuidRoute =
  AuthenticatedCompanyRolesUuidRouteImport.update({
    id: '/company-roles/$uuid',
    path: '/company-roles/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesCreateRoute =
  AuthenticatedCompaniesCreateRouteImport.update({
    id: '/companies/create',
    path: '/companies/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesUuidRoute =
  AuthenticatedCompaniesUuidRouteImport.update({
    id: '/companies/$uuid',
    path: '/companies/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsRouteRoute =
  AuthenticatedDemoSettingsRouteRouteImport.update({
    id: '/demo/settings',
    path: '/demo/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoUsersIndexRoute =
  AuthenticatedDemoUsersIndexRouteImport.update({
    id: '/demo/users/',
    path: '/demo/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoTasksIndexRoute =
  AuthenticatedDemoTasksIndexRouteImport.update({
    id: '/demo/tasks/',
    path: '/demo/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsIndexRoute =
  AuthenticatedDemoSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoHelpCenterIndexRoute =
  AuthenticatedDemoHelpCenterIndexRouteImport.update({
    id: '/demo/help-center/',
    path: '/demo/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoChatsIndexRoute =
  AuthenticatedDemoChatsIndexRouteImport.update({
    id: '/demo/chats/',
    path: '/demo/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoAppsIndexRoute =
  AuthenticatedDemoAppsIndexRouteImport.update({
    id: '/demo/apps/',
    path: '/demo/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsNotificationsRoute =
  AuthenticatedDemoSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsDisplayRoute =
  AuthenticatedDemoSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAppearanceRoute =
  AuthenticatedDemoSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAccountRoute =
  AuthenticatedDemoSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedCompaniesCompanyUuidRolesIndexRoute =
  AuthenticatedCompaniesCompanyUuidRolesIndexRouteImport.update({
    id: '/companies/$companyUuid/roles/',
    path: '/companies/$companyUuid/roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesCompanyUuidRolesCreateRoute =
  AuthenticatedCompaniesCompanyUuidRolesCreateRouteImport.update({
    id: '/companies/$companyUuid/roles/create',
    path: '/companies/$companyUuid/roles/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesCompanyUuidRolesUuidRoute =
  AuthenticatedCompaniesCompanyUuidRolesUuidRouteImport.update({
    id: '/companies/$companyUuid/roles/$uuid',
    path: '/companies/$companyUuid/roles/$uuid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/companies/$uuid': typeof AuthenticatedCompaniesUuidRoute
  '/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/company-roles/$uuid': typeof AuthenticatedCompanyRolesUuidRoute
  '/company-roles/create': typeof AuthenticatedCompanyRolesCreateRoute
  '/global-roles/$uuid': typeof AuthenticatedGlobalRolesUuidRoute
  '/global-roles/create': typeof AuthenticatedGlobalRolesCreateRoute
  '/posts/$uuid': typeof AuthenticatedPostsUuidRoute
  '/posts/create': typeof AuthenticatedPostsCreateRoute
  '/projects/$uuid': typeof AuthenticatedProjectsUuidRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/tickets/$uuid': typeof AuthenticatedTicketsUuidRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/company-members': typeof AuthenticatedCompanyMembersIndexRoute
  '/company-roles': typeof AuthenticatedCompanyRolesIndexRoute
  '/file-library': typeof AuthenticatedFileLibraryIndexRoute
  '/global-roles': typeof AuthenticatedGlobalRolesIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/demo/apps': typeof AuthenticatedDemoAppsIndexRoute
  '/demo/chats': typeof AuthenticatedDemoChatsIndexRoute
  '/demo/help-center': typeof AuthenticatedDemoHelpCenterIndexRoute
  '/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksIndexRoute
  '/demo/users': typeof AuthenticatedDemoUsersIndexRoute
  '/companies/$companyUuid/roles/$uuid': typeof AuthenticatedCompaniesCompanyUuidRolesUuidRoute
  '/companies/$companyUuid/roles/create': typeof AuthenticatedCompaniesCompanyUuidRolesCreateRoute
  '/companies/$companyUuid/roles': typeof AuthenticatedCompaniesCompanyUuidRolesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/companies/$uuid': typeof AuthenticatedCompaniesUuidRoute
  '/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/company-roles/$uuid': typeof AuthenticatedCompanyRolesUuidRoute
  '/company-roles/create': typeof AuthenticatedCompanyRolesCreateRoute
  '/global-roles/$uuid': typeof AuthenticatedGlobalRolesUuidRoute
  '/global-roles/create': typeof AuthenticatedGlobalRolesCreateRoute
  '/posts/$uuid': typeof AuthenticatedPostsUuidRoute
  '/posts/create': typeof AuthenticatedPostsCreateRoute
  '/projects/$uuid': typeof AuthenticatedProjectsUuidRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/tickets/$uuid': typeof AuthenticatedTicketsUuidRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/company-members': typeof AuthenticatedCompanyMembersIndexRoute
  '/company-roles': typeof AuthenticatedCompanyRolesIndexRoute
  '/file-library': typeof AuthenticatedFileLibraryIndexRoute
  '/global-roles': typeof AuthenticatedGlobalRolesIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/demo/apps': typeof AuthenticatedDemoAppsIndexRoute
  '/demo/chats': typeof AuthenticatedDemoChatsIndexRoute
  '/demo/help-center': typeof AuthenticatedDemoHelpCenterIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsIndexRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksIndexRoute
  '/demo/users': typeof AuthenticatedDemoUsersIndexRoute
  '/companies/$companyUuid/roles/$uuid': typeof AuthenticatedCompaniesCompanyUuidRolesUuidRoute
  '/companies/$companyUuid/roles/create': typeof AuthenticatedCompaniesCompanyUuidRolesCreateRoute
  '/companies/$companyUuid/roles': typeof AuthenticatedCompaniesCompanyUuidRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/_authenticated/companies/$uuid': typeof AuthenticatedCompaniesUuidRoute
  '/_authenticated/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/_authenticated/company-roles/$uuid': typeof AuthenticatedCompanyRolesUuidRoute
  '/_authenticated/company-roles/create': typeof AuthenticatedCompanyRolesCreateRoute
  '/_authenticated/global-roles/$uuid': typeof AuthenticatedGlobalRolesUuidRoute
  '/_authenticated/global-roles/create': typeof AuthenticatedGlobalRolesCreateRoute
  '/_authenticated/posts/$uuid': typeof AuthenticatedPostsUuidRoute
  '/_authenticated/posts/create': typeof AuthenticatedPostsCreateRoute
  '/_authenticated/projects/$uuid': typeof AuthenticatedProjectsUuidRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/tickets/$uuid': typeof AuthenticatedTicketsUuidRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/company-members/': typeof AuthenticatedCompanyMembersIndexRoute
  '/_authenticated/company-roles/': typeof AuthenticatedCompanyRolesIndexRoute
  '/_authenticated/file-library/': typeof AuthenticatedFileLibraryIndexRoute
  '/_authenticated/global-roles/': typeof AuthenticatedGlobalRolesIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/posts/': typeof AuthenticatedPostsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/_authenticated/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/_authenticated/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/_authenticated/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/_authenticated/demo/apps/': typeof AuthenticatedDemoAppsIndexRoute
  '/_authenticated/demo/chats/': typeof AuthenticatedDemoChatsIndexRoute
  '/_authenticated/demo/help-center/': typeof AuthenticatedDemoHelpCenterIndexRoute
  '/_authenticated/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/_authenticated/demo/tasks/': typeof AuthenticatedDemoTasksIndexRoute
  '/_authenticated/demo/users/': typeof AuthenticatedDemoUsersIndexRoute
  '/_authenticated/companies/$companyUuid/roles/$uuid': typeof AuthenticatedCompaniesCompanyUuidRolesUuidRoute
  '/_authenticated/companies/$companyUuid/roles/create': typeof AuthenticatedCompaniesCompanyUuidRolesCreateRoute
  '/_authenticated/companies/$companyUuid/roles/': typeof AuthenticatedCompaniesCompanyUuidRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/demo/settings'
    | '/companies/$uuid'
    | '/companies/create'
    | '/company-roles/$uuid'
    | '/company-roles/create'
    | '/global-roles/$uuid'
    | '/global-roles/create'
    | '/posts/$uuid'
    | '/posts/create'
    | '/projects/$uuid'
    | '/projects/create'
    | '/tickets/$uuid'
    | '/audit-logs'
    | '/companies'
    | '/company-members'
    | '/company-roles'
    | '/file-library'
    | '/global-roles'
    | '/locations'
    | '/posts'
    | '/projects'
    | '/users'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/help-center'
    | '/demo/settings/'
    | '/demo/tasks'
    | '/demo/users'
    | '/companies/$companyUuid/roles/$uuid'
    | '/companies/$companyUuid/roles/create'
    | '/companies/$companyUuid/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/companies/$uuid'
    | '/companies/create'
    | '/company-roles/$uuid'
    | '/company-roles/create'
    | '/global-roles/$uuid'
    | '/global-roles/create'
    | '/posts/$uuid'
    | '/posts/create'
    | '/projects/$uuid'
    | '/projects/create'
    | '/tickets/$uuid'
    | '/audit-logs'
    | '/companies'
    | '/company-members'
    | '/company-roles'
    | '/file-library'
    | '/global-roles'
    | '/locations'
    | '/posts'
    | '/projects'
    | '/users'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/help-center'
    | '/demo/settings'
    | '/demo/tasks'
    | '/demo/users'
    | '/companies/$companyUuid/roles/$uuid'
    | '/companies/$companyUuid/roles/create'
    | '/companies/$companyUuid/roles'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/demo/settings'
    | '/_authenticated/companies/$uuid'
    | '/_authenticated/companies/create'
    | '/_authenticated/company-roles/$uuid'
    | '/_authenticated/company-roles/create'
    | '/_authenticated/global-roles/$uuid'
    | '/_authenticated/global-roles/create'
    | '/_authenticated/posts/$uuid'
    | '/_authenticated/posts/create'
    | '/_authenticated/projects/$uuid'
    | '/_authenticated/projects/create'
    | '/_authenticated/tickets/$uuid'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/companies/'
    | '/_authenticated/company-members/'
    | '/_authenticated/company-roles/'
    | '/_authenticated/file-library/'
    | '/_authenticated/global-roles/'
    | '/_authenticated/locations/'
    | '/_authenticated/posts/'
    | '/_authenticated/projects/'
    | '/_authenticated/users/'
    | '/_authenticated/demo/settings/account'
    | '/_authenticated/demo/settings/appearance'
    | '/_authenticated/demo/settings/display'
    | '/_authenticated/demo/settings/notifications'
    | '/_authenticated/demo/apps/'
    | '/_authenticated/demo/chats/'
    | '/_authenticated/demo/help-center/'
    | '/_authenticated/demo/settings/'
    | '/_authenticated/demo/tasks/'
    | '/_authenticated/demo/users/'
    | '/_authenticated/companies/$companyUuid/roles/$uuid'
    | '/_authenticated/companies/$companyUuid/roles/create'
    | '/_authenticated/companies/$companyUuid/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/': {
      id: '/_authenticated/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/global-roles/': {
      id: '/_authenticated/global-roles/'
      path: '/global-roles'
      fullPath: '/global-roles'
      preLoaderRoute: typeof AuthenticatedGlobalRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/file-library/': {
      id: '/_authenticated/file-library/'
      path: '/file-library'
      fullPath: '/file-library'
      preLoaderRoute: typeof AuthenticatedFileLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-roles/': {
      id: '/_authenticated/company-roles/'
      path: '/company-roles'
      fullPath: '/company-roles'
      preLoaderRoute: typeof AuthenticatedCompanyRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-members/': {
      id: '/_authenticated/company-members/'
      path: '/company-members'
      fullPath: '/company-members'
      preLoaderRoute: typeof AuthenticatedCompanyMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/$uuid': {
      id: '/_authenticated/tickets/$uuid'
      path: '/tickets/$uuid'
      fullPath: '/tickets/$uuid'
      preLoaderRoute: typeof AuthenticatedTicketsUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$uuid': {
      id: '/_authenticated/projects/$uuid'
      path: '/projects/$uuid'
      fullPath: '/projects/$uuid'
      preLoaderRoute: typeof AuthenticatedProjectsUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/create': {
      id: '/_authenticated/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof AuthenticatedPostsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/$uuid': {
      id: '/_authenticated/posts/$uuid'
      path: '/posts/$uuid'
      fullPath: '/posts/$uuid'
      preLoaderRoute: typeof AuthenticatedPostsUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/global-roles/create': {
      id: '/_authenticated/global-roles/create'
      path: '/global-roles/create'
      fullPath: '/global-roles/create'
      preLoaderRoute: typeof AuthenticatedGlobalRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/global-roles/$uuid': {
      id: '/_authenticated/global-roles/$uuid'
      path: '/global-roles/$uuid'
      fullPath: '/global-roles/$uuid'
      preLoaderRoute: typeof AuthenticatedGlobalRolesUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-roles/create': {
      id: '/_authenticated/company-roles/create'
      path: '/company-roles/create'
      fullPath: '/company-roles/create'
      preLoaderRoute: typeof AuthenticatedCompanyRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-roles/$uuid': {
      id: '/_authenticated/company-roles/$uuid'
      path: '/company-roles/$uuid'
      fullPath: '/company-roles/$uuid'
      preLoaderRoute: typeof AuthenticatedCompanyRolesUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/create': {
      id: '/_authenticated/companies/create'
      path: '/companies/create'
      fullPath: '/companies/create'
      preLoaderRoute: typeof AuthenticatedCompaniesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$uuid': {
      id: '/_authenticated/companies/$uuid'
      path: '/companies/$uuid'
      fullPath: '/companies/$uuid'
      preLoaderRoute: typeof AuthenticatedCompaniesUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings': {
      id: '/_authenticated/demo/settings'
      path: '/demo/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof AuthenticatedDemoSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/users/': {
      id: '/_authenticated/demo/users/'
      path: '/demo/users'
      fullPath: '/demo/users'
      preLoaderRoute: typeof AuthenticatedDemoUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/tasks/': {
      id: '/_authenticated/demo/tasks/'
      path: '/demo/tasks'
      fullPath: '/demo/tasks'
      preLoaderRoute: typeof AuthenticatedDemoTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings/': {
      id: '/_authenticated/demo/settings/'
      path: '/'
      fullPath: '/demo/settings/'
      preLoaderRoute: typeof AuthenticatedDemoSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/help-center/': {
      id: '/_authenticated/demo/help-center/'
      path: '/demo/help-center'
      fullPath: '/demo/help-center'
      preLoaderRoute: typeof AuthenticatedDemoHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/chats/': {
      id: '/_authenticated/demo/chats/'
      path: '/demo/chats'
      fullPath: '/demo/chats'
      preLoaderRoute: typeof AuthenticatedDemoChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/apps/': {
      id: '/_authenticated/demo/apps/'
      path: '/demo/apps'
      fullPath: '/demo/apps'
      preLoaderRoute: typeof AuthenticatedDemoAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings/notifications': {
      id: '/_authenticated/demo/settings/notifications'
      path: '/notifications'
      fullPath: '/demo/settings/notifications'
      preLoaderRoute: typeof AuthenticatedDemoSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/display': {
      id: '/_authenticated/demo/settings/display'
      path: '/display'
      fullPath: '/demo/settings/display'
      preLoaderRoute: typeof AuthenticatedDemoSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/appearance': {
      id: '/_authenticated/demo/settings/appearance'
      path: '/appearance'
      fullPath: '/demo/settings/appearance'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/account': {
      id: '/_authenticated/demo/settings/account'
      path: '/account'
      fullPath: '/demo/settings/account'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/companies/$companyUuid/roles/': {
      id: '/_authenticated/companies/$companyUuid/roles/'
      path: '/companies/$companyUuid/roles'
      fullPath: '/companies/$companyUuid/roles'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyUuidRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$companyUuid/roles/create': {
      id: '/_authenticated/companies/$companyUuid/roles/create'
      path: '/companies/$companyUuid/roles/create'
      fullPath: '/companies/$companyUuid/roles/create'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyUuidRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$companyUuid/roles/$uuid': {
      id: '/_authenticated/companies/$companyUuid/roles/$uuid'
      path: '/companies/$companyUuid/roles/$uuid'
      fullPath: '/companies/$companyUuid/roles/$uuid'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyUuidRolesUuidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedDemoSettingsRouteRouteChildren {
  AuthenticatedDemoSettingsAccountRoute: typeof AuthenticatedDemoSettingsAccountRoute
  AuthenticatedDemoSettingsAppearanceRoute: typeof AuthenticatedDemoSettingsAppearanceRoute
  AuthenticatedDemoSettingsDisplayRoute: typeof AuthenticatedDemoSettingsDisplayRoute
  AuthenticatedDemoSettingsNotificationsRoute: typeof AuthenticatedDemoSettingsNotificationsRoute
  AuthenticatedDemoSettingsIndexRoute: typeof AuthenticatedDemoSettingsIndexRoute
}

const AuthenticatedDemoSettingsRouteRouteChildren: AuthenticatedDemoSettingsRouteRouteChildren =
  {
    AuthenticatedDemoSettingsAccountRoute:
      AuthenticatedDemoSettingsAccountRoute,
    AuthenticatedDemoSettingsAppearanceRoute:
      AuthenticatedDemoSettingsAppearanceRoute,
    AuthenticatedDemoSettingsDisplayRoute:
      AuthenticatedDemoSettingsDisplayRoute,
    AuthenticatedDemoSettingsNotificationsRoute:
      AuthenticatedDemoSettingsNotificationsRoute,
    AuthenticatedDemoSettingsIndexRoute: AuthenticatedDemoSettingsIndexRoute,
  }

const AuthenticatedDemoSettingsRouteRouteWithChildren =
  AuthenticatedDemoSettingsRouteRoute._addFileChildren(
    AuthenticatedDemoSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoSettingsRouteRoute: typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  AuthenticatedCompaniesUuidRoute: typeof AuthenticatedCompaniesUuidRoute
  AuthenticatedCompaniesCreateRoute: typeof AuthenticatedCompaniesCreateRoute
  AuthenticatedCompanyRolesUuidRoute: typeof AuthenticatedCompanyRolesUuidRoute
  AuthenticatedCompanyRolesCreateRoute: typeof AuthenticatedCompanyRolesCreateRoute
  AuthenticatedGlobalRolesUuidRoute: typeof AuthenticatedGlobalRolesUuidRoute
  AuthenticatedGlobalRolesCreateRoute: typeof AuthenticatedGlobalRolesCreateRoute
  AuthenticatedPostsUuidRoute: typeof AuthenticatedPostsUuidRoute
  AuthenticatedPostsCreateRoute: typeof AuthenticatedPostsCreateRoute
  AuthenticatedProjectsUuidRoute: typeof AuthenticatedProjectsUuidRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedTicketsUuidRoute: typeof AuthenticatedTicketsUuidRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedCompanyMembersIndexRoute: typeof AuthenticatedCompanyMembersIndexRoute
  AuthenticatedCompanyRolesIndexRoute: typeof AuthenticatedCompanyRolesIndexRoute
  AuthenticatedFileLibraryIndexRoute: typeof AuthenticatedFileLibraryIndexRoute
  AuthenticatedGlobalRolesIndexRoute: typeof AuthenticatedGlobalRolesIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedPostsIndexRoute: typeof AuthenticatedPostsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedDemoAppsIndexRoute: typeof AuthenticatedDemoAppsIndexRoute
  AuthenticatedDemoChatsIndexRoute: typeof AuthenticatedDemoChatsIndexRoute
  AuthenticatedDemoHelpCenterIndexRoute: typeof AuthenticatedDemoHelpCenterIndexRoute
  AuthenticatedDemoTasksIndexRoute: typeof AuthenticatedDemoTasksIndexRoute
  AuthenticatedDemoUsersIndexRoute: typeof AuthenticatedDemoUsersIndexRoute
  AuthenticatedCompaniesCompanyUuidRolesUuidRoute: typeof AuthenticatedCompaniesCompanyUuidRolesUuidRoute
  AuthenticatedCompaniesCompanyUuidRolesCreateRoute: typeof AuthenticatedCompaniesCompanyUuidRolesCreateRoute
  AuthenticatedCompaniesCompanyUuidRolesIndexRoute: typeof AuthenticatedCompaniesCompanyUuidRolesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoSettingsRouteRoute:
    AuthenticatedDemoSettingsRouteRouteWithChildren,
  AuthenticatedCompaniesUuidRoute: AuthenticatedCompaniesUuidRoute,
  AuthenticatedCompaniesCreateRoute: AuthenticatedCompaniesCreateRoute,
  AuthenticatedCompanyRolesUuidRoute: AuthenticatedCompanyRolesUuidRoute,
  AuthenticatedCompanyRolesCreateRoute: AuthenticatedCompanyRolesCreateRoute,
  AuthenticatedGlobalRolesUuidRoute: AuthenticatedGlobalRolesUuidRoute,
  AuthenticatedGlobalRolesCreateRoute: AuthenticatedGlobalRolesCreateRoute,
  AuthenticatedPostsUuidRoute: AuthenticatedPostsUuidRoute,
  AuthenticatedPostsCreateRoute: AuthenticatedPostsCreateRoute,
  AuthenticatedProjectsUuidRoute: AuthenticatedProjectsUuidRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedTicketsUuidRoute: AuthenticatedTicketsUuidRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedCompanyMembersIndexRoute: AuthenticatedCompanyMembersIndexRoute,
  AuthenticatedCompanyRolesIndexRoute: AuthenticatedCompanyRolesIndexRoute,
  AuthenticatedFileLibraryIndexRoute: AuthenticatedFileLibraryIndexRoute,
  AuthenticatedGlobalRolesIndexRoute: AuthenticatedGlobalRolesIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedPostsIndexRoute: AuthenticatedPostsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedDemoAppsIndexRoute: AuthenticatedDemoAppsIndexRoute,
  AuthenticatedDemoChatsIndexRoute: AuthenticatedDemoChatsIndexRoute,
  AuthenticatedDemoHelpCenterIndexRoute: AuthenticatedDemoHelpCenterIndexRoute,
  AuthenticatedDemoTasksIndexRoute: AuthenticatedDemoTasksIndexRoute,
  AuthenticatedDemoUsersIndexRoute: AuthenticatedDemoUsersIndexRoute,
  AuthenticatedCompaniesCompanyUuidRolesUuidRoute:
    AuthenticatedCompaniesCompanyUuidRolesUuidRoute,
  AuthenticatedCompaniesCompanyUuidRolesCreateRoute:
    AuthenticatedCompaniesCompanyUuidRolesCreateRoute,
  AuthenticatedCompaniesCompanyUuidRolesIndexRoute:
    AuthenticatedCompaniesCompanyUuidRolesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
